export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

export const ATTENDANCE_USER_REQUEST = "ATTENDANCE_USER_REQUEST";
export const ATTENDANCE_USER_SUCCESS = "ATTENDANCE_USER_SUCCESS";
export const ATTENDANCE_USER_FAIL = "ATTENDANCE_USER_FAIL";
